### ISSUE TITLE
[Feat] 선수 선택 뷰 리디자인(v1.1.0)

### ISSUE THREAD

**Issue by eemdeeks** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#102]
## 💡 Issue

선수 선택 뷰 UX에 따른 뷰 리디자인

## 📝 Todo
- [x] 선수 선택 뷰 디자인 변경
- [x] 선수 선택 뷰 기능
- [x] 선수 클릭시 기능
- [x] 선수 비어있을 때 뷰 적용
