### ISSUE TITLE
[Feat] v1.1.0 수정 요소 반영

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#103]
## 💡 Issue
- v1.1.0을 위한 합의된 내용을 바탕으로 수정을 진행합니다.

## 📝 Todo
- [x] 탭 순서 변경 -> 팀관리 - 선수 - 유니폼 - 테마 
- [x] 편집 시, 마지막 탭 선택 들어가기
- [x] 포메이션 추가(풋살 버젼)
