### ISSUE TITLE
[Feat] 1차 디자인 디테일 수정

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#106]
## 💡 Issue
- 디자인 디테일을 수정합니다.

## 📝 Todo
- [x] 골키퍼 하단 Offset 수정
- [x] 편집 화면에서의 왼쪽 상단 헤더 텍스트 하단 패딩 수정
- [x] 선수 네임태그 상하 (1.5x) 좌우 (1.1x) 패딩 수정
- [x] 밀어올려서 편집하기 텍스트 상단 패딩 (0.6x) 수정 및 SF Symbol 수정
- [x] 공유하기 버튼의 SF Symbol - 텍스트 사이 패딩 (1.25x) 조정
- [x] 유니폼 (테두리, Primary, Secondary) 중 Primary에만 그림자 추가
- [x] TeanInfoView 간격 수정
