### ISSUE TITLE
[Feat] 유니폼 커스텀을 위한 ColorPicker 구현

### ISSUE THREAD

**Issue by sozohoy** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#11]
## 💡 Issue
- 유니폼 에셋을 커스텀할 수 있도록 ColorPicker를 이용하여 SVG를 변환하는 작업을 진행합니다.

## 📝 Todo
- [ ] ColorPicker 구현
- [ ] SVG 색상 변경
- [ ] 유니폼과 관련된 모델 재정의
- [ ] 유니폼 커스텀 기능 구현
