### ISSUE TITLE
[Feat] 선수 등록 및 선택 기능

### ISSUE THREAD

**Issue by eemdeeks** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#29]
## 💡 Issue

선수를 등록하고 선수를 선택해서 포메이션에 넣는 기능을 구현하기 위한 이슈입니다 :]

## 📝 Todo
- [x] 선수 등록 기능
- [x] 선수 삭제 기능
- [x] 선수 편집 기능
- [x] 선수 선택 기능
- [x] 선수 선택 시 선수 완료 기능
- [x] 선수 선택 시 이미 있던 선수 비워 주기
