### ISSUE TITLE
[Refactor] 메인뷰 코드 개선

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#47]
## 💡 Issue
- 메인뷰 코드 개선을 위한 이슈 입니다.

## 📝 Todo
- [x] 기존 바인딩을 위한 State 변수들을 Observable로 교체하여 코드 개선
- [x] NavigationView 삭제, ZStack ->  VStack
- [x] 상태값 변수 주석 
- [x] 중복코드 개선
