### ISSUE TITLE
[Feat] 버그 및 디자인 수정

### ISSUE THREAD

**Issue by eemdeeks** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#69]
## 💡 Issue

기능을 합치면서 생긴 버그를 고치고 계속해서 디자인 수정을 할 예정입니다.

## 📝 Todo
- [x] 선수가 경기장 밖을 나가버리는 버그 해결
- [x] editSheet 드래그 인터렉션 수정
- [x] 메인 뷰 타이틀, 서브타이틀 디자인 수정
- [x] editSheet올라올 경우 캐러셀 인터렉션 불가하도록 수정
- [x] 캐러셀 민감도 수정
- [x] shareView 테마에 따라 뒷 배경 변경안되는 것 수정
- [x] 공유하기 버튼 블러처리
- [x] 메인 화면에서 편집모드에서만 선수들 draggable
- [x] 팀 이름 최대치 정해주기
