### ISSUE TITLE
[Fix] ShareView 수정 요소

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#70]
## 💡 Issue
- ShareView 수정 요소 반영

## 📝 Todo
- [x] ShareSheet 로컬라이징 대응(영어로만 나오는 현상 해결)
- [x] ShareSheet 사진 저장 
- [x] ShareImage 여백 나오는 현상 수정
- [x] ShareImage 객체 반응형 오프셋 수정
