### ISSUE TITLE
[Feat] 팀관리 기능 완성

### ISSUE THREAD

**Issue by sozohoy** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#71]
## 💡 Issue
- 팀 관리 기능을 완성합니다

## 📝 Todo
- [ ] player fetch시 순서대로 내려오는지 확인
- [ ] 포메이션 저장
- [ ] 팀명 변경 기능
- [ ] 스쿼드명 변경 기능
