### ISSUE TITLE
[Feat] 선수추가, 선택 SwiftData연동

### ISSUE THREAD

**Issue by eemdeeks** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#73]
## 💡 Issue

팀에 선수 추가, 선택 기능에 SwiftData를 연동하겠습니다!!!

## 📝 Todo
- [x] 선수리스트 모델 추가
- [x] 선수 추가 SiwftData연동
- [x] 스쿼드에 있는 선수마다 분기처리 기능
