### ISSUE TITLE
[QA] 호환성, 성능 및 기능 테스트

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#87]
## 💡 Issue
- 배포 전, 호환성/ 성능 및 기능 테스트를 실시합니다.

## 📝 Todo
- **호환성 테스트**
    - [ ] iOS 버전 및 디바이스에서의 호환성 확인.
    - [ ] 화면 크기 및 해상도에 따른 앱의 반응성 테스트.
    - [ ] 로컬라이징 적용 여부 테스트.
-  **성능 테스트**
    - [ ] 앱 속도 및 반응성 테스트.
    - [ ] 메모리 사용량 및 배터리 소모량 테스트.
- **기능 테스트**
    - [ ] 앱의 모든 기능이 명세와 일치하는지 검증.
    - [ ] 버튼, 메뉴, 입력 필드 등의 인터페이스 요소들이 정확하게 동작하는지 확인.

- 인터페이스 및 사용성 테스트는 1차 배포 후, 실시합니다.
