### ISSUE TITLE
[Release] v1.0.1 Hotfix

### ISSUE THREAD

**Issue by eemdeeks** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#92]
## 💡 Issue

v1.0.1을 위한 이슈입니다.

## 📝 Todo
- [x] 다크모드 시 UI 바뀌는 현상 해결
- [x] 선수선택 뷰에서만 수정할 선수 선택 가능하게 하기
- [x] 유니폼, 팀관리, 테마 수정 뷰로 옮길 경우 선수 선택 없애주기
